### ISSUE TITLE
Undefined function exponential_backoff

### ISSUE THREAD

**Issue by bpardee** [spreedly/kaffe#106]
I upgraded from 1.18.0 to  1.19.0 and started getting the following crash

```
{
    "crash_reason": "{%UndefinedFunctionError{arity: 0, function: :exponential_backoff, message: nil, module: Retry.DelayStreams, reason: nil}, [{Retry.DelayStreams, :exponential_backoff, [], []}, {Kaffe.GroupManager, :subscribe_to_topics, 2, [file: 'lib/kaffe/consumer_group/group_manager.ex', line: 135]}, {Kaffe.GroupManager, :handle_cast, 2, [file: 'lib/kaffe/consumer_group/group_manager.ex', line: 105]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 689]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 765]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}]}",
    "level": "error",
    "message": "GenServer :\"Elixir.Kaffe.GroupManager.portfolio-monitor-consumer-group\" terminating\n** (UndefinedFunctionError) function Retry.DelayStreams.exponential_backoff/0 is undefined (module Retry.DelayStreams is not available)\n    Retry.DelayStreams.exponential_backoff()\n    (kaffe 1.19.0) lib/kaffe/consumer_group/group_manager.ex:135: Kaffe.GroupManager.subscribe_to_topics/2\n    (kaffe 1.19.0) lib/kaffe/consumer_group/group_manager.ex:105: Kaffe.GroupManager.handle_cast/2\n    (stdlib 3.14) gen_server.erl:689: :gen_server.try_dispatch/4\n    (stdlib 3.14) gen_server.erl:765: :gen_server.handle_msg/6\n    (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3\nLast message: {:\"$gen_cast\", {:start_group_members}}",
    "registered_name": ":\"Elixir.Kaffe.GroupManager.portfolio-monitor-consumer-group\"",
    "timestamp": "2021-01-30T16:31:00.463085Z"
}
```

**Comment by objectuser** [comment]
@bpardee Interesting, that should be part of a new dependency on `retry`. Did that come down for you when you did a `mix deps.get`?

**Comment by bpardee** [comment]
Yes, here are the applicable diffs:
```
-  "brod": {:hex, :brod, "3.14.0", "f959408e88acd0feca22f6a43ca26e70201c6e5c57dc74b87f08ef65a5e7fe18", [:rebar3], [{:kafka_protocol, "2.3.6", [hex: :kafka_protocol, repo: "hexpm", optional: false]}, {:supervisor3, "1.1.11", [hex: :supervisor3, repo: "hexpm", optional: false]}], "hexpm", "a0153437835b810d93e79c7000f55b0c4bd62c281a3224a2615f6aa72b52d484"},
+  "brod": {:hex, :brod, "3.15.1", "073b0e16f4193291a05e01ae36351ddba1bda85ad4f90f66566c8123a335150e", [:rebar3], [{:kafka_protocol, "2.3.6", [hex: :kafka_protocol, repo: "hexpm", optional: false]}, {:supervisor3, "1.1.11", [hex: :supervisor3, repo: "hexpm", optional: false]}], "hexpm", "170216364cb9c72201ab59416ec7283d5e3fc094406b03210df6be0347234c4e"},
-  "kaffe": {:hex, :kaffe, "1.18.0", "c6064797e5e0e0b625df8de1b9bff2d0b5e48104ea28e8677d9db73e641b263e", [:mix], [{:brod, "~> 3.0", [hex: :brod, repo: "hexpm", optional: false]}], "hexpm", "fccf831ee0d9c07374c6a60c1be1bb878051db43f2ec3d563a45bd9ae5271c55"},
+  "kaffe": {:hex, :kaffe, "1.19.0", "688bbb7a39ff40d9e3524f22ec4df44726681de96b8a823acff0cd53c4c4a69c", [:mix], [{:brod, "~> 3.0", [hex: :brod, repo: "hexpm", optional: false]}, {:retry, "~> 0.14.1", [hex: :retry, repo: "hexpm", optional: false]}], "hexpm", "5cb802ba01c3cc1f951d94811751f2cfa81c9a978252a3d77c641bcaa6693da2"},
   "kafka_protocol": {:hex, :kafka_protocol, "2.3.6", "df076a8ef49fffae3535c805cb00f3a057ce1895e63398bf8a10569eeeac02f8", [:rebar, :rebar3], [{:crc32cer, "0.1.4", [hex: :crc32cer, repo: "hexpm", optional: false]}, {:snappyer, "1.2.5", [hex: :snappyer, repo: "hexpm", optional: false]}], "hexpm", "7cb061fe46babc7fd269d2c0e5b4dba5d1efc4f7dacce85b17a9cca973106b23"},
+  "retry": {:hex, :retry, "0.14.1", "722d1b0cf87096b71213f5801d99fface7ca76adc83fc9dbf3e1daee952aef10", [:mix], [], "hexpm", "b3a609f286f6fe4f6b2c15f32cd4a8a60427d78d05d7b68c2dd9110981111ae0"},
```

**Comment by andyleclair** [comment]
FWIW I have also noticed this today

**Comment by objectuser** [comment]
@fatcatt316 Maybe introduced with the `retry` changes ...

**Comment by fatcatt316** [comment]
@objectuser Hmm, maybe 🤔  We're a bit busy now, but I'm adding this to our list to take a look at when time permits...

**Comment by objectuser** [comment]
@bpardee @andyleclair Care to dig in and PR? 😁

**Comment by andyleclair** [comment]
from what I can infer from a brief reading of the code I'd guess that `use Retry` is maybe not working right. My guess is that because `Retry`'s `__using__` macro doesn't `require Retry` before calling `import Retry` the `retry` macro isn't imported correctly and that has knock-on effects. Unsure why it'd look like that though

**Comment by redmaner** [comment]
Are you using mix release @bpardee?

**Comment by bpardee** [comment]
@redmaner Yes we are using mix release

**Comment by redmaner** [comment]
@bpardee add retry to `extra_applications` in mix.exs of the application or library that imports Kaffe will fix your issue you described.

As stated in my comment above, to fix this on Kaffe's level retry needs to be added to `extra_applications` of Kaffe's mix.exs.
